version: '3.8'

services:
  app:
    build:
      context: .
    container_name: log-collector
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    command: ["/wait-for-it.sh", "db:3306", "--", "./main"]


  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: logdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
